name: aoc2019

dependencies:
- base >= 4.7 && < 5
- vector
- containers
- mtl
- parsec

default-extensions:
- RecordWildCards
- RankNTypes
- ParallelListComp
- FlexibleContexts

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall

executables:
  aoc2019:
    main:                Main.hs
    source-dirs:         ./
