name: aoc2019

dependencies:
- base >= 4.7 && < 5
- vector
- containers

executables:
  aoc2019:
    main:                Main.hs
    source-dirs:         ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - vector
    - containers
